[package]
name = "spambotsen"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
sqlx = { version = "0.6.2", features = [
    "runtime-tokio-native-tls",
    "postgres",
] }
shuttle-service = { version = "0.9.0", features = ["bot-serenity"] }
anyhow = "1.0.68"
serenity = { version = "0.11.5", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
shuttle-secrets = "0.9.0"
tracing = "0.1.37"
csv = "1.1.6"
rand = "0.8.5"
shuttle-static-folder = "0.9.0"
serde = "1.0.152"
